// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_Uqpj5TiCBYbO68ONY6XoszeybX0FX0',
    appId: '1:397715137176:web:531ad307dcbc69be27e6ed',
    messagingSenderId: '397715137176',
    projectId: 'madinatyconnect',
    authDomain: 'madinatyconnect.firebaseapp.com',
    storageBucket: 'madinatyconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4V8dDiNvmM-6ErQl8r486HYZZUyGk7Bo',
    appId: '1:397715137176:android:9b0be3d0f581621c27e6ed',
    messagingSenderId: '397715137176',
    projectId: 'madinatyconnect',
    storageBucket: 'madinatyconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwpTwvfa8TEWV5JSLw8esjit4erHVG_tM',
    appId: '1:397715137176:ios:621de60d233d203827e6ed',
    messagingSenderId: '397715137176',
    projectId: 'madinatyconnect',
    storageBucket: 'madinatyconnect.firebasestorage.app',
    iosBundleId: 'com.example.madinatyconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwpTwvfa8TEWV5JSLw8esjit4erHVG_tM',
    appId: '1:397715137176:ios:621de60d233d203827e6ed',
    messagingSenderId: '397715137176',
    projectId: 'madinatyconnect',
    storageBucket: 'madinatyconnect.firebasestorage.app',
    iosBundleId: 'com.example.madinatyconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ_Uqpj5TiCBYbO68ONY6XoszeybX0FX0',
    appId: '1:397715137176:web:42434243213cd12927e6ed',
    messagingSenderId: '397715137176',
    projectId: 'madinatyconnect',
    authDomain: 'madinatyconnect.firebaseapp.com',
    storageBucket: 'madinatyconnect.firebasestorage.app',
  );

}